import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./components/header";
import { Categories } from "./components/categories";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`antialised`}>
        <Header />
        <div className="pt-4">
          <Categories />
        </div>

        {/* Conteúdos */}
        {children}


      </body>
    </html>
  );
}
